// cant improt css file here import in _app.js
import Head from 'next/head'
import Image from 'next/image'

import Paths from "./Paths";

export default function Header(){
	return(
		<>  
			<Head>
		        <meta name="description" content="Generated by create next app" />
		        <link rel="icon" href="/favicon.ico" />
		        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
		        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />
		        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" />
	      	</Head>

			<header className='header'>

				<span>DIT Global Next</span>
				<Paths />
			</header>
			
		</>
	)
}
// if u want sparte nav than <Paths /> put out sid of header tag and change in Paths.js file 